config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :postings
  resources :users
  root :to      => 'home#about'

  get "login"   => "sessions#new",        :as => "login"
  post '/login' => "sessions#create"
  get "logout"  => "sessions#destroy",    :as => "logout"
  get "signup"  => "users#new",           :as => "signup"
  resources :sessions
  get "secret" => "home#secret", :as => "secret"
  
  get 'home/about'

  get 'home/index'

end

app/models/posting.rb
class Posting < ActiveRecord::Base
	has_attached_file :attachment#, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :attachment, content_type: /\Aapplication\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!


  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
 	validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 

before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_url # halts request cycle
    end
  end


  private
  def not_authenticated
    redirect_to login_url, :alert => "You need to log in to view this page."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :require_login, :only => :secret

  def about
  end

  def index
  end

  def secret
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
 

  # GET /postings
  # GET /postings.json
  def index
    @posting = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    @posting = Posting.find(params[:id])
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
    @posting = Posting.find(params[:id])
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)


    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      @posting = Posting.find(params[:id])
      if @posting.update_attributes(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @postings.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
    def destroy
      @posting = Posting.find(params[:id])
      @posting.destroy
      redirect_to :postings, notice: "Successfully deleted!!!"
    end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @postings = Posting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :location, :contact, :url, :notes, :date_applied, :company, :attachment)
    end

    def user_params
      params.require(:user).permit(:attachment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
  	@user = User.new
  end

	def create
     user = login(params[:email], params[:password])
    if user
      redirect_back_or_to users_url, :notice => "Logged in!"
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
   end

   def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  	end



	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => :secret
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :lastname, :birthdate, :email, :password, :password_confirmation)
    end

    
end


def activate
  if (@user = User.load_from_activation_token(params[:id]))
    @user.activate!
    redirect_to(login_path, :notice => 'User was successfully activated.')
  else
    not_authenticated
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



<head>
  <title>Employment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>


</body>
</html>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>



<%= render 'form' %>



<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>


<p><a href="/">Back Home</a></p>

app/views/postings/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <style> 

    html {  
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    table {
      table-layout: fixed;
      color:midnightblue;
      -webkit-border-radius: 13;
      -moz-border-radius: 13;
      font-family: Tahoma;
      color: midnightblue;
      font-size: 22px;
      text-decoration: none;
    }

    table{
        margin:2px 0 0 0;
    }

    footer  {
      margin: 100px
    }

    .info {
      color: dimgrey;
      font-size: 24px;
    }

    .row  {
    }
    img   {        
      width: 100%; 
      height: 100%;
      overflow: auto;
    }
  </style>
</head>
<body>
  <div class ="container">
    <nav class="navbar navbar-default navbar-static-top">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#">Pete Camp </a>
       <br>
       <br>
     </div>
     <div id="navbar" class="navbar-collapse collapse">
       <ul class="nav navbar-nav">
    <li class="warning"><%= link_to 'New Job Posting', new_posting_path(@posting) %></li>
    <li class="active"><%= link_to 'Back to All Users', users_path(@user) %></li>
         <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li class="dropdown-header">Education and Job Search</li>
          <li><a href="#">Link to Star City Code School</a></li>
          <li><a href="#">Job Search Links</a></li>
          <li class="dropdown-header">Portfolio</li>
          <li><a href="#">Soccer Management System</a></li>
          <li><a href="http://camp91783.github.io/w07-d03-tic-tac-toe/">Tic Tac Toe</a></li>
          <li class="dropdown-header">Resources & Media</li>
          <li><a href="http://careerlink.com/lp/brilliant-people-omaha-sumeet-jain-talks-founding-omaha-code-school-advice-new-developers/?utm_source=constantcontact&utm_medium=email&utm_term=brilliantppl&utm_campaign=jobseeker">Interview with School Founder Summeet Jain</a></li>
          <li><a href="http://siliconprairienews.com/2016/01/omaha-code-school-opens-star-city-code-school-in-lincoln/">Interview with Instructor Andrew Ek</a></li>

           </ul>
         </li>
       </ul>
       <ul class="nav navbar-nav navbar-right">
        <li class="warning"><%= link_to 'Logout', logout_path(@sessions) %></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </nav>
 </div>
<div class="row">

  <div class="col-md-12">
    <img src="http://luxurycouncil.com/wp-content/uploads/2013/06/chicago-dusk.jpg" class="img-responsive"></img>
  </div>
</div>
<div class="table-responsive">
  <table class = "table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Company</th>
      </tr>
    </thead>


  <tbody>
    <% @posting.each do |posting| %>
      <tr>
        <td><%=link_to posting.title ,posting %></td>
        <td><%= posting.company %></td>
      </tr>
        <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
      <% end %>
    </tbody>
  </table>
</div>

<br>
    
 <div class="row">
    <div class="img">
      <div class="col-md-12">
      <img src="http://static1.squarespace.com/static/53ee9cece4b09d1f241db239/5408ab44e4b04f2a4fea902a/55e7a154e4b0f4565e4c312f/1441244028438/?format=1500w" class="img-responsive"></img>
    </div>
  </div>
</div>
<div id="footer">
  <div class="container">
    <p class="text-muted">Link to Peter Camp Github Account <a href="https://github.com/Camp91783/jobs.git">GitHub</a></p>
  </div>
</div>

</body>

</html>

app/views/postings/show.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>

<body>


<div class="container">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<style type="text/css">
<style> 

td {
  background-color: blue;

}
.info {
  color: dimgrey;
  font-size: 24px;
}

.row  {
}

img   {        
width: 100%; 
height: 100%;
overflow: auto;
  }

.active {
  color: red !important;
}

</style>

<head>
<nav class="navbar navbar-default navbar-static-top">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Pete Camp </a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Edit', edit_posting_path(@posting) %><Job Postings</a></li>
      <li class="warning"><%= link_to 'New Job Posting', new_posting_path(@posting) %></li>
      <li class="warning"><%= link_to 'Back to All Jobs', postings_path(@posting) %></li>
      <li class="active"><%= link_to 'Back to All Users', users_path(@user) %></li>
           <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Education and Job Search</li>
            <li><a href="#">Link to Star City Code School</a></li>
            <li><a href="#">Job Search Links</a></li>
            <li class="dropdown-header">Portfolio</li>
            <li><a href="#">Soccer Management System</a></li>
            <li><a href="http://camp91783.github.io/w07-d03-tic-tac-toe/">Tic Tac Toe</a></li>
            <li class="dropdown-header">Resources & Media</li>
            <li><a href="http://careerlink.com/lp/brilliant-people-omaha-sumeet-jain-talks-founding-omaha-code-school-advice-new-developers/?utm_source=constantcontact&utm_medium=email&utm_term=brilliantppl&utm_campaign=jobseeker">Interview with School Founder Summeet Jain</a></li>
            <li><a href="http://siliconprairienews.com/2016/01/omaha-code-school-opens-star-city-code-school-in-lincoln/">Interview with Instructor Andrew Ek</a></li>
             </ul>
           </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li class="active"><a href="/logout">Logout <span class="sr-only">(current)</span></a></li>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>
  <head>
     <title></title>
  </head>

  <div class="row">
    <div class="img">
      <div class="col-md-12">
      <img src="http://www.jetblue.com/img/vacations/destination/New-Orleans-960-x-420.jpg" class="img-responsive"></img>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="info">
      <div class="col-md-4"><p>
        <br>
        <font color="black">
      <td><strong>Title:</strong></td></font>
      <td><strong><%= @posting.title %></strong></td></p>
    </div>
    <div class="col-md-4"><p>
    <br>
      <font color="black">
      <td><strong>Company:</strong></td></font>
      <td><strong><%= @posting.company %></strong></td>
      </td>
    </p></div>
      <div class="col-md-4"><p>
        <br>
       <font color="black">
      <td><strong>Location:</strong></td></font>
    <td><strong><%= @posting.location %></strong></td> 
      </p></div>
    </div>
  </div>
  </div>
  <br>
  <br>
  <div class="container">
  <div class="row">
  <div class="info">
    <div class="col-md-4"><p>
      <br>
      <font color="black">
      <td><strong>Contact:</strong></td></font>
      <td><strong><%= @posting.contact %></strong></td>
    </p></div>
    <div class="col-md-4"><p>
    <br>
    <font color="black">
      <td><strong>Url:</strong></td></font>
      <td><strong><%= @posting.url %></strong></td>
    </p></div>
      <div class="col-md-4"><p>
      <br>
      <font color="black">
        <td><strong>Notes:</strong></td></font>
        <td><strong><%= @posting.notes %></strong></td>
        </p></div>
      <div class="col-md-4"><p>


      <% if @posting.attachment %>

<p>
  <strong>Cover Letter:</strong>
    <%= link_to "Attached File", @posting.attachment.url %>
</p>

<% end %>

    </div>
  </div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
  </div>
  <div class="row">
    <div class="col-md-6"></div>
    <div class="col-md-6"></div>
  </div>
</div>
 <div class="row">
    <div class="img">
      <div class="col-md-12">
      <img src="http://cdn.totalfratmove.com/wp-content/uploads/2011/07/dd3e7fe85b31a3c0144282390b48ea79412901799.jpg"></img>
    </div>
  </div>
</div>









<div id="footer">
  <div class="container">
    <p class="text-muted">Link to Peter Camp Github Account <a href="https://github.com/Camp91783/jobs.git">GitHub</a></p>
  </div>
</div>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>


<p><a href="/">Back Home</a></p>

app/views/users/index.html.erb
<!DOCTYPE html>
<style> 

img   {        
width: 100%; 
height: 50%%;
overflow: auto;
  }

ul  {

}

}
</style>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Pete Camp</a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
          <li class="warning"><%= link_to 'New Job Posting', new_posting_path(@posting) %></li>
          <li class="warning"><%= link_to 'Saved Jobs', postings_path(@posting) %></li>
          <li class="active"><%= link_to 'Create a New User', new_user_path(@user) %></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Education and Job Search</li>
            <li><a href="#">Link to Star City Code School</a></li>
            <li><a href="#">Job Search Links</a></li>
            <li class="dropdown-header">Portfolio</li>
            <li><a href="#">Soccer Management System</a></li>
            <li><a href="http://camp91783.github.io/w07-d03-tic-tac-toe/">Tic Tac Toe</a></li>
            <li class="dropdown-header">Resources & Media</li>
            <li><a href="http://careerlink.com/lp/brilliant-people-omaha-sumeet-jain-talks-founding-omaha-code-school-advice-new-developers/?utm_source=constantcontact&utm_medium=email&utm_term=brilliantppl&utm_campaign=jobseeker">Interview with School Founder Summeet Jain</a></li>
            <li><a href="http://siliconprairienews.com/2016/01/omaha-code-school-opens-star-city-code-school-in-lincoln/">Interview with Instructor Andrew Ek</a></li>
          </ul>
            <li class="warning"><%= link_to 'Logout', logout_path(@sessions) %></li>

         </ul>
       </div><!--/.nav-collapse -->
     </div>
     <div class="row">
        <div class="img">
          <div class="col-md-12">
            <img src="http://fc3d750e1b22019028ae-eb9d0534c31fede444754f378d638c42.r70.cf1.rackcdn.com/uploads/picture/source/1284/San_Francisco_-_Golden_Gate_Bridge.jpg" class="img-responsive"></img>
          </div>
        </div>
      </div>
      <li><a href="postings">Saved Jobs</a></li>
      <div class="col-md-4">
        <div class="container">
          <div class="row">
              <br>
                <font color="black">
                <h4>Registered Users</h4></font>
                <strong>Username / Name</strong></font>
                <a><li><strong><% @users.each do |user| %></strong></li></a>
                <a><li><strong><%= user.username %></strong></li></a>
                <% end %>
              <br>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="container">
           <div class="row">
          </div>
        </div>
      </div>
      <div class="col-md-4">
      </div>
  <div class="row">
    <div class="img">
      <div class="container">
      <div class="col-md-12">
        <img src="https://seattlesteve.files.wordpress.com/2014/02/dsc03070.jpg" class ="img-responsive"></img>
      </div>
      </div>
    </div>
  </div>
  </div>
<div id="footer">
  <div class="container">
    <p class="text-muted">Link to Peter Camp Github Account <a href="https://github.com/Camp91783/jobs.git">GitHub</a></p>
  </div>
</div>
</body>
</html>
 

app/views/users/show.html.erb
<!DOCTYPE html>
<style> 


</style>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="BootstrapBay.com">
    <link href="css/bootstrap.min.css" rel="stylesheet">
  </head>
  <body>
  <head>
<nav class="navbar navbar-default navbar-static-top">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Pete Camp </a>
       </div>
       <div id="navbar" class="navbar-collapse collapse">
         <ul class="nav navbar-nav">
      <li class="warning"><%= link_to 'New Job Posting', new_posting_path(@posting) %></li>
      <li class="warning"><%= link_to 'Back to All Jobs', postings_path(@posting) %></li>
      <li class="active"><%= link_to 'Back to All Users', users_path(@user) %></li>
           <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="dropdown-header">Education and Job Search</li>
            <li><a href="#">Link to Star City Code School</a></li>
            <li><a href="#">Job Search Links</a></li>
            <li class="dropdown-header">Portfolio</li>
            <li><a href="#">Soccer Management System</a></li>
            <li><a href="http://camp91783.github.io/w07-d03-tic-tac-toe/">Tic Tac Toe</a></li>
            <li class="dropdown-header">Resources & Media</li>
            <li><a href="http://careerlink.com/lp/brilliant-people-omaha-sumeet-jain-talks-founding-omaha-code-school-advice-new-developers/?utm_source=constantcontact&utm_medium=email&utm_term=brilliantppl&utm_campaign=jobseeker">Interview with School Founder Summeet Jain</a></li>
            <li><a href="http://siliconprairienews.com/2016/01/omaha-code-school-opens-star-city-code-school-in-lincoln/">Interview with Instructor Andrew Ek</a></li>
             </ul>
           </li>
         </ul>
         <ul class="nav navbar-nav navbar-right">
           <li class="active"><a href="/logout">Logout <span class="sr-only">(current)</span></a></li>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>
  <head>
  <div class="row">
    <div class="img">
      <div class="col-md-12">
      <img src="http://www.tourist-destinations.net/wp-content/uploads/2013/07/waikiki.jpg" class="img-responsive"></img>
    </div>
  </div>
</div>
     <title></title>
  </head>
<p id="notice"><%= notice %></p>
<div class="container">
    <p>
      <strong>Username:</strong>
      <%= @user.username %>
    </p>

    <p>
      <strong>Lastname:</strong>
      <%= @user.lastname %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>
</div>
<br>
<br>
<br>

<p><a href="/postings">All Saved Jobs</a></p>
<p><a href="/users">All Saved Users</a></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<p><a href="/">Back Home</a></p>